/***************************************************************************
 *     Copyright (c) 1999-2011, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Sat Feb 19 03:49:23 2011
 *                 MD5 Checksum         204fcd82dd9e6918d23f64a37bd16883
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef BCHP_SDIO_1_CFG_H__
#define BCHP_SDIO_1_CFG_H__

/***************************************************************************
 *SDIO_1_CFG - SDIO (eMMC) Configuration Registers
 ***************************************************************************/
#define BCHP_SDIO_1_CFG_SDIO_EMMC_CTRL1          0x00205d00 /* SDIO EMMC Control Register */
#define BCHP_SDIO_1_CFG_SDIO_EMMC_CTRL2          0x00205d04 /* SDIO EMMC Control Register */
#define BCHP_SDIO_1_CFG_TP_OUT_SEL               0x00205d08 /* SDIO TP_OUT Control Register */
#define BCHP_SDIO_1_CFG_CAP_REG0                 0x00205d0c /* SDIO CAPABILITIES override Register */
#define BCHP_SDIO_1_CFG_CAP_REG1                 0x00205d10 /* SDIO CAPABILITIES override Register */
#define BCHP_SDIO_1_CFG_PRESET1                  0x00205d14 /* SDIO CAPABILITIES override Register */
#define BCHP_SDIO_1_CFG_PRESET2                  0x00205d18 /* SDIO CAPABILITIES override Register */
#define BCHP_SDIO_1_CFG_SD_CLOCK_DELAY           0x00205d1c /* SDIO Clock delay register */
#define BCHP_SDIO_1_CFG_SD_PAD_DRV               0x00205d20 /* SDIO Clock delay register */
#define BCHP_SDIO_1_CFG_IP_DLY                   0x00205d30 /* SDIO Host input delay register */
#define BCHP_SDIO_1_CFG_OP_DLY                   0x00205d34 /* SDIO Host output delay register */
#define BCHP_SDIO_1_CFG_SCRATCH                  0x00205dfc /* SDIO Scratch Register */
#define BCHP_SDIO_1_CFG_VERSION                  0x00205df0 /* SDIO VERSION Register */

#endif /* #ifndef BCHP_SDIO_1_CFG_H__ */

/* End of File */
