obj-y			+= bchip.o board.o irq.o prom.o setup.o time.o \
	sysfs.o memory.o power.o vector.o memc1.o m2m.o
obj-$(CONFIG_PCI)	+= pci.o
obj-$(CONFIG_SMP)	+= smp.o
obj-$(CONFIG_BRCM_HAS_STANDBY)	+= standby.o
obj-$(CONFIG_BRCM_HAS_AON) += s3_standby.o s3.o
